version: "3.7"
services:
    db:
      image: mariadb:10.5
      container_name: db
      restart: always
      environment:
       MARIADB_ROOT_PASSWORD: root
       MYSQL_DATABASE: rh-data
      ports:
        - 3306:3306
